import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import localFont from "next/font/local";
import "./globals.css";

const mona = localFont({
  src: [
    {
      path: "./Mona-Sans-LightWide.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./Mona-Sans-MediumWide.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./Mona-Sans-BoldWide.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-mona",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale} className={mona.variable}>
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
